plugins: fetchart embedart convert scrub replaygain lastgenre chroma web ftintitle
directory: /music/media
library: /config/library/musiclibrary.db
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no

convert:
    auto: yes
    format: flac
    never_convert_lossy_files: yes

paths:
    default: $albumartist - $album%aunique{}/$track - $title
    singleton: $albumartist - Singles/$title
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title

import:
    write: yes
    copy: yes
    move: no
    resume: no
    incremental: no
    duplicate_action: skip
    quiet_fallback: skip
    timid: no
    log: /config/beet.log

ftintitle:
  format: (feat. {0})

lastgenre:
    auto: yes
    source: album

embedart:
    auto: yes

fetchart:
    auto: yes

replaygain:
    auto: no

scrub:
    auto: yes

match:
    strong_rec_thresh: 0.10

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''

web:
    host: 0.0.0.0
    port: 8337
